services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: postgres_db
    restart: always
    # Se cargan las variables desde el archivo .env de la raíz
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Persistencia en un directorio local específico mediante volumenes
    volumes:
      - ./.data/postgres:/var/lib/postgresql
    # Se mapea el puerto del contenedor al host para acceso local desde el .env
    ports:
      - "${POSTGRES_PORT}:5432"


